### ISSUE TITLE
Remove client parameter check

### ISSUE THREAD

**Issue by sewi-cpan** [elastic/elasticsearch-perl#171]
Please consider removing the client-side parameter checking at all. It's causing lots of trouble with nearly no win (see #169 for example).
Upgrading the client module isn't always as easy as it looks like due to the heavy dependencies.

**Comment by ezimuel** [comment]
@sewi-cpan this is an interesting point, I would like to improve this part. I think it's important to have a feature that provides a check for the parameter since it makes no sense to send a request with an invalid body. I will update `elasticsearch-perl` on a regular basis and this issue will be mitigated.
I'm investigating also the possibility to have some autocompletion feature with the parameters. Do you have any idea about that? Thanks!

**Comment by sewi-cpan** [comment]
@ezimuel Problems start when Elasticsearch expects different arguments than the client module. Invalid arguments should usually happen in development. Errors due to invalid arguments are unlikely to happen in production.
The argument check causes serious trouble while switching from one Elasticsearch version to another or using clusters with different major versions (one already upgraded, the other one not upgraded).
