### ISSUE TITLE
Compatibility needs hacking to work (Client 7.3 ==> Server 6.8)

### ISSUE THREAD

**Issue by truj** [elastic/elasticsearch-perl#198]
I'm trying to use Search::Elasticsearch 7.3 together with Elasticsearch 6.8.
Referring to [this comment](https://github.com/elastic/elasticsearch-perl/issues/192#issuecomment-685431986), I've tried
```
my $es = Search::Elasticsearch->new(
    client => '6_0::Direct',
    %other_settings,
);
```
But I get this error:
Can't locate Search/Elasticsearch/Client/6_0/Direct.pm

Checking the install, I found out that there is indeed no file **6_0.pm** inside of **blib/lib/Search/Elasticsearch/Client/**.
So I copied **Search/Elasticsearch/Client/6_0.pm** and (recursively) **Search/Elasticsearch/Client/6_0/** from an old installation (Client version 6.8) to the new installation (Client version 7.3).
Now it seems to work.

My suggestion:
Include the newest 6.x client code into the 7.x client as well, so that the compatibility mode is working without hacks.
This is especially useful for upgrade scenarios like ours.
We try to minimize our down time during the upgrade. So we upgrade in several steps:
- status quo: client 6.8 + server 6.8
- client 7.3 in compatibility mode + server 6.8
- client 7.3 in normal mode + server 6.8

**Comment by ezimuel** [comment]
@truj thanks for reporting this. I'm investigating the issue, I'll update asap.

**Comment by ezimuel** [comment]
@truj since I'm building Client versions with different packages, you need to install `Search::Elasticsearch::Client::6_0` manually after the installation of `Search::Elasticsearch`. Basically, the `Search::Elasticsearch` package will install the latest version (`7`), if you want the previous one (`6`) you need to require explicitly.

Using `cpanm` you can type the following command:
```bash
cpanm Search::Elasticsearch::Client::6_0
```
This will add the `Client::6_0` support into the previous `Search::Elasticsearch` installation.

**Comment by truj** [comment]
Great, thank you for the explanation.
