### ISSUE TITLE
$info        = $e->cluster->info;

### ISSUE THREAD

**Issue by GeorgeBouras** [elastic/elasticsearch-perl#216]
From the module documentation
    ...
    $info   = $e->cluster->info;
    ....
    Can't locate object method "info" via package "Search::Elasticsearch::Client::7_0::Direct::Cluster"

Thanks, George Bouras

**Comment by jenswitzel** [comment]
Dear George

Never used, but quickly tested and I can confirm.

[Mon Nov 15 17:03:42.109002 2021] [:error] [pid 9031] Can't locate object
method "info" via package
"Search::Elasticsearch::Client::7_0::Direct::Cluster" at [....]\n

Thanks
 Jens

--
Jens Witzel
Zentrale Informatik
Universität Zürich
Stampfenbachstrasse 73
CH-8006 Zürich

mail:  ***@***.***
phone: +41 44 63 56777
http://www.zi.uzh.ch



Von:	"George Bouras" ***@***.***>
An:	"elastic/elasticsearch-perl"
            ***@***.***>
Kopie:	"Subscribed" ***@***.***>
Datum:	15.11.2021 15:13
Betreff:	[elastic/elasticsearch-perl] $info        = $e->cluster->info;
            (Issue #216)



From the module documentation
...
$info = $e->cluster->info;
....
Can't locate object method "info" via package
"Search::Elasticsearch::Client::7_0::Direct::Cluster"


Thanks, George Bouras


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ezimuel** [comment]
@GeorgeBouras the `cluster` namespace in 7.x do not provide an `info` endpoint. The `info` endpoint is in `nodes`, [nodes.info](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/cluster-nodes-info.html). The `cluster` namespace has [cluster.state](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/cluster-state.html) and [cluster.health](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/cluster-health.html) that can be useful as well.
